<?php declare(strict_types=1);
require __DIR__.'/../src/ProblemException.php';require __DIR__.'/../src/Client.php';
use Phessage\HeadlessCommerce\Client;use Phessage\HeadlessCommerce\ProblemException;
$assert=function(bool $value,string $message):void{if(!$value)throw new RuntimeException($message);};
$bootstrapCalls=[];Client::forStore('store-a','https://bootstrap.test',function(string $url,array $headers,string $method,?string $body)use(&$bootstrapCalls):array{$bootstrapCalls[]=[$url,$headers,$method,$body];return ['status'=>200,'body'=>'{"data":{"storeId":"store-a","apiUrl":"https://sandbox.test","publishableKey":"pk_test_demo","apiVersion":"v1","capabilities":["catalog","cart","checkout-preparation"]}}'];});$assert(str_ends_with($bootstrapCalls[0][0],'/v1/headless/stores/store-a/config'),'store bootstrap route failed');
$calls=[];$client=new Client('https://sandbox.test','pk_test_demo',function(string $url,array $headers)use(&$calls):array{$calls[]=[$url,$headers];return ['status'=>200,'body'=>json_encode(['data'=>[['id'=>'p1','name'=>'Pack']],'nextCursor'=>null,'requestId'=>'req_1'],JSON_THROW_ON_ERROR)];});
$page=$client->listProducts(999,null,' pack ');$assert($page['data'][0]['name']==='Pack','product parsing failed');$assert(str_contains($calls[0][0],'/v1/headless/products?limit=100&query=pack'),'URL contract failed');$assert($calls[0][1]['x-publishable-key']==='pk_test_demo','key header missing');
$attempts=0;$client=new Client('https://sandbox.test','pk_test_demo',function()use(&$attempts):array{$attempts++;return $attempts===1?['status'=>503,'body'=>'{}','headers'=>['Retry-After'=>'0']]:['status'=>404,'body'=>'{"type":"x","title":"Missing","requestId":"body-id"}','headers'=>['X-Request-Id'=>'header-id','RateLimit-Limit'=>'100','RateLimit-Remaining'=>'0','RateLimit-Reset'=>'42','Retry-After'=>'7']];},1);try{$client->listProducts();throw new RuntimeException('expected exception');}catch(ProblemException $e){$assert($e->status===404&&$e->requestId==='header-id','header-first correlation failed');$assert($e->rateLimit===['limit'=>100,'remaining'=>0,'reset'=>42,'retryAfter'=>'7'],'rate diagnostics failed');}$assert($attempts===2,'safe retry failed');
try{new Client('https://sandbox.test','secret');throw new RuntimeException('expected invalid key');}catch(InvalidArgumentException){}
$routes=[];$client=new Client('https://sandbox.test','pk_test_demo',function(string $url)use(&$routes):array{$routes[]=$url;return ['status'=>200,'body'=>'{"data":[],"requestId":"r"}'];});$client->getProduct('p/1');$client->listCategories();$assert(str_ends_with($routes[0],'/v1/headless/products/p%2F1'),'detail route failed');$assert(str_ends_with($routes[1],'/v1/headless/products/categories'),'category route failed');
$composer=json_decode(file_get_contents(__DIR__.'/../composer.json'),true,512,JSON_THROW_ON_ERROR);$assert($composer['extra']['laravel']['providers'][0]==='Phessage\\HeadlessCommerce\\Laravel\\HeadlessCommerceServiceProvider','Laravel discovery missing');if(!function_exists('env')){function env($key,$default=null){return $default;}}$config=require __DIR__.'/../config/headless-commerce.php';$assert(array_key_exists('base_url',$config),'Laravel config missing');
$cartCalls=[];$client=new Client('https://sandbox.test','pk_test_demo',function(string $url,array $headers,string $method,?string $body)use(&$cartCalls):array{$cartCalls[]=[$url,$headers,$method,$body];return ['status'=>200,'body'=>'{"data":{"id":"cart-1","items":[]},"requestId":"r"}'];});$token='hc_'.str_repeat('a',43);$client->addCartItem($token,'product-1',2);$assert($cartCalls[0][2]==='POST'&&$cartCalls[0][1]['x-cart-token']===$token,'cart mutation headers failed');$assert(json_decode($cartCalls[0][3],true)['quantity']===2,'cart mutation body failed');
$mutationAttempts=0;$client=new Client('https://sandbox.test','pk_test_demo',function()use(&$mutationAttempts):array{$mutationAttempts++;return ['status'=>503,'body'=>'{}'];},2);try{$client->createCart();throw new RuntimeException('expected mutation failure');}catch(ProblemException $e){$assert($e->status===503,'mutation problem failed');}$assert($mutationAttempts===1,'mutation was retried');
$checkoutCalls=[];$client=new Client('https://sandbox.test','pk_test_demo',function(string $url,array $headers,string $method,?string $body)use(&$checkoutCalls):array{$checkoutCalls[]=[$url,$headers,$method,$body];return ['status'=>200,'body'=>'{"data":{"ready":false,"missing":[]},"requestId":"r"}'];});$client->getCheckoutPreparation($token);$client->updateCheckoutDetails($token,['billingAddress'=>['country'=>'CA']]);$client->selectCheckoutShippingMethod($token,'ship-id');$client->selectCheckoutPaymentMethod($token,'pay-id');$assert(array_map(fn(array $call):array=>[$call[2],parse_url($call[0],PHP_URL_PATH)],$checkoutCalls)===[['GET','/v1/headless/carts/current/checkout'],['PATCH','/v1/headless/carts/current/checkout'],['PUT','/v1/headless/carts/current/checkout/shipping-method'],['PUT','/v1/headless/carts/current/checkout/payment-method']],'checkout routes failed');$assert(json_decode($checkoutCalls[2][3],true)['id']==='ship-id','checkout selection body failed');
$orderCalls=[];$attempt=0;$client=new Client('https://sandbox.test','pk_test_demo',function(string $url,array $headers,string $method,?string $body)use(&$orderCalls,&$attempt):array{$orderCalls[]=[$url,$headers,$method,$body];$attempt++;return $attempt===1?['status'=>503,'body'=>'{}']:['status'=>201,'body'=>'{"data":{"orderNumber":"ORD1","paymentStatus":"pending","requiresPayment":false},"requestId":"r"}'];},1);$order=$client->placeOrder($token,'intent-1');$assert($order['data']['orderNumber']==='ORD1'&&count($orderCalls)===2,'order retry failed');$assert($orderCalls[0][1]['Idempotency-Key']==='intent-1'&&$orderCalls[1][1]['Idempotency-Key']==='intent-1','order key changed');try{$client->placeOrder($token,' ');throw new RuntimeException('expected invalid key');}catch(InvalidArgumentException){}
$lookupCalls=[];$client=new Client('https://sandbox.test','pk_test_demo',function(string $url,array $headers,string $method,?string $body)use(&$lookupCalls):array{$lookupCalls[]=[$url,$headers,$method,$body];return ['status'=>201,'body'=>'{"data":{"orderNumber":"ORD1","status":"pending","items":[],"tracking":null},"requestId":"r"}'];},2);$lookup=$client->lookupOrder(' ORD1 ','buyer@example.test');$assert($lookup['data']['status']==='pending'&&count($lookupCalls)===1,'order lookup failed');$assert($lookupCalls[0][2]==='POST'&&str_ends_with($lookupCalls[0][0],'/v1/headless/orders/lookup'),'lookup route failed');$assert(json_decode($lookupCalls[0][3],true)===['orderNumber'=>'ORD1','email'=>'buyer@example.test'],'lookup body failed');try{$client->lookupOrder('ORD1','bad');throw new RuntimeException('expected invalid email');}catch(InvalidArgumentException){}
echo "11 tests passed\n";
