<?php declare(strict_types=1);
require __DIR__.'/../src/ProblemException.php';require __DIR__.'/../src/Client.php';
use Phessage\HeadlessCommerce\Client;use Phessage\HeadlessCommerce\ProblemException;
$assert=function(bool $value,string $message):void{if(!$value)throw new RuntimeException($message);};
$calls=[];$client=new Client('https://sandbox.test','pk_test_demo',function(string $url,array $headers)use(&$calls):array{$calls[]=[$url,$headers];return ['status'=>200,'body'=>json_encode(['data'=>[['id'=>'p1','name'=>'Pack']],'nextCursor'=>null,'requestId'=>'req_1'],JSON_THROW_ON_ERROR)];});
$page=$client->listProducts(999,null,' pack ');$assert($page['data'][0]['name']==='Pack','product parsing failed');$assert(str_contains($calls[0][0],'/v1/headless/products?limit=100&query=pack'),'URL contract failed');$assert($calls[0][1]['x-publishable-key']==='pk_test_demo','key header missing');
$attempts=0;$client=new Client('https://sandbox.test','pk_test_demo',function()use(&$attempts):array{$attempts++;return $attempts===1?['status'=>503,'body'=>'{}']:['status'=>404,'body'=>'{"type":"x","title":"Missing","requestId":"req_2"}'];},1);try{$client->listProducts();throw new RuntimeException('expected exception');}catch(ProblemException $e){$assert($e->status===404&&$e->requestId==='req_2','typed problem failed');}$assert($attempts===2,'safe retry failed');
try{new Client('https://sandbox.test','secret');throw new RuntimeException('expected invalid key');}catch(InvalidArgumentException){}
$routes=[];$client=new Client('https://sandbox.test','pk_test_demo',function(string $url)use(&$routes):array{$routes[]=$url;return ['status'=>200,'body'=>'{"data":[],"requestId":"r"}'];});$client->getProduct('p/1');$client->listCategories();$assert(str_ends_with($routes[0],'/v1/headless/products/p%2F1'),'detail route failed');$assert(str_ends_with($routes[1],'/v1/headless/products/categories'),'category route failed');
$composer=json_decode(file_get_contents(__DIR__.'/../composer.json'),true,512,JSON_THROW_ON_ERROR);$assert($composer['extra']['laravel']['providers'][0]==='Phessage\\HeadlessCommerce\\Laravel\\HeadlessCommerceServiceProvider','Laravel discovery missing');if(!function_exists('env')){function env($key,$default=null){return $default;}}$config=require __DIR__.'/../config/headless-commerce.php';$assert(array_key_exists('base_url',$config),'Laravel config missing');
echo "5 tests passed\n";
